---
version: "3.3"
services:
  amsocr:
    restart: always
    container_name: amsocr
    image: cmccambridge/ocrmypdf-auto
    volumes:
      - "/media/ocr/input:/input"
      - "/media/ocr/output:/output"
      - "/media/ocr/archive:/archive"
      - "/media/ocr/logs:/logs"
      - "/media/ocr/config:/config"
    environment:
      - OCR_LANGUAGES=eng grc ell swe 
      - OCR_OUTPUT_MODE=MIRROR_TREE
      - OCR_PROCESS_EXISTING_ON_START=1
      - OCR_USE_POLLING_SCHEDULER=1
      - OCR_ACTION_ON_SUCCESS=ARCHIVE_INPUT_FILES
      - USERMAP_UID=1000
      - USERMAP_GID=1000
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Athens
    volumes:
      - /var/syncthing/config:/config
      #- /media/ocr/input:/data/input_pdf
      #- /media/ocr/output:/data/output_pdf
    volumes_from:
      - amsocr
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: always